spring:
  datasource:
    url: jdbc:h2:mem:taplistdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: ${BMS_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    client-id: taplist-dev
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        delivery.timeout.ms: 120000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false
    properties:
      security.protocol: PLAINTEXT

logging:
  level:
    org.springframework.security: DEBUG

bms:
  kafka:
    enabled: ${BMS_KAFKA_ENABLED:true}
    retention: P7D
    domains:
      - prodinventory
      - keginventory
      - taproom
      - catalog
      - sales
      - distribution
      - procurement
      - maintenance
      - analytics
      - billing
      - compliance
      - iam
    sample:
      enabled: ${BMS_KAFKA_SAMPLE_ENABLED:false}
      brewery-id: ${BMS_KAFKA_SAMPLE_BREWERY:00000000-0000-0000-0000-000000000001}
      facility-id: ${BMS_KAFKA_SAMPLE_FACILITY:00000000-0000-0000-0000-000000000010}
  ui:
    component-library:
      enabled: ${BMS_UI_COMPONENT_LIBRARY_ENABLED:true}
