spring:
  datasource:
    url: jdbc:postgresql://localhost:${STAGING_POSTGRES_PORT:5433}/${STAGING_POSTGRES_DB:mythic_staging}
    username: ${STAGING_POSTGRES_USER:bms}
    password: ${STAGING_POSTGRES_PASSWORD:changeme-staging}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  h2:
    console:
      enabled: false

springdoc:
  enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

bms:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
    allowed-methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
    allowed-headers: ["*"]
    allow-credentials: true
