spring:
  datasource:
    url: jdbc:postgresql://localhost:${STAGING_POSTGRES_PORT:5433}/${STAGING_POSTGRES_DB:mythic_staging}
    username: ${STAGING_POSTGRES_USER:bms}
    password: ${STAGING_POSTGRES_PASSWORD:changeme-staging}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  h2:
    console:
      enabled: false
  kafka:
    bootstrap-servers: ${BMS_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    client-id: taplist-staging
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        delivery.timeout.ms: 120000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false
    properties:
      security.protocol: PLAINTEXT

springdoc:
  swagger-ui:
    enabled: true

bms:
  kafka:
    enabled: ${BMS_KAFKA_ENABLED:false}
    retention: P7D
