spring:
  datasource:
    url: jdbc:postgresql://localhost:${PRODUCTION_POSTGRES_PORT:5432}/${PRODUCTION_POSTGRES_DB:mythic_prod}
    username: ${PRODUCTION_POSTGRES_USER:bms}
    password: ${PRODUCTION_POSTGRES_PASSWORD:changeme-prod}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
  h2:
    console:
      enabled: false

springdoc:
  enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

bms:
  cors:
    allowed-origins: []
    allowed-methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
    allowed-headers: ["*"]
    allow-credentials: true
