spring:
  datasource:
    url: jdbc:postgresql://localhost:${STAGING_POSTGRES_PORT:5433}/${STAGING_POSTGRES_DB:mythic_staging}
    username: ${STAGING_POSTGRES_USER:bms}
    password: ${STAGING_POSTGRES_PASSWORD:changeme-staging}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  h2:
    console:
      enabled: false

springdoc:
  swagger-ui:
    enabled: true

