spring:
  datasource:
    url: jdbc:h2:mem:taplistdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG
