-- Catalog: Recipes to support BeerXML and BeerSmith imports

create table if not exists recipe (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  style_name varchar(255),
  type varchar(64),
  batch_size_liters double precision,
  boil_time_minutes integer,
  ibu double precision,
  abv double precision,
  og double precision,
  fg double precision,
  efficiency double precision,
  equipment varchar(255),
  source_format varchar(32),
  source_hash varchar(255),
  notes varchar(4000),
  created_at timestamp not null,
  brewery_id bigint not null,
  constraint fk_recipe_brewery foreign key (brewery_id) references brewery(id)
);

create table if not exists recipe_fermentable (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null,
  name varchar(255) not null,
  amount_kg double precision,
  yield_percent double precision,
  color_lovibond double precision,
  late_addition boolean,
  type varchar(64),
  constraint fk_rf_recipe foreign key (recipe_id) references recipe(id)
);
create index if not exists idx_rf_recipe on recipe_fermentable(recipe_id);

create table if not exists recipe_hop (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null,
  name varchar(255) not null,
  alpha_acid double precision,
  amount_grams double precision,
  time_minutes integer,
  use_for varchar(64),
  form varchar(64),
  ibu_contribution double precision,
  constraint fk_rh_recipe foreign key (recipe_id) references recipe(id)
);
create index if not exists idx_rh_recipe on recipe_hop(recipe_id);

create table if not exists recipe_yeast (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null,
  name varchar(255),
  laboratory varchar(255),
  product_id varchar(128),
  type varchar(64),
  form varchar(64),
  attenuation double precision,
  constraint fk_ry_recipe foreign key (recipe_id) references recipe(id)
);
create index if not exists idx_ry_recipe on recipe_yeast(recipe_id);

create table if not exists recipe_misc (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null,
  name varchar(255),
  type varchar(64),
  amount double precision,
  amount_unit varchar(32),
  use_for varchar(64),
  constraint fk_rm_recipe foreign key (recipe_id) references recipe(id)
);
create index if not exists idx_rm_recipe on recipe_misc(recipe_id);

create table if not exists mash_step (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null,
  name varchar(255),
  type varchar(64),
  step_temp_c double precision,
  step_time_minutes integer,
  infuse_amount_liters double precision,
  constraint fk_ms_recipe foreign key (recipe_id) references recipe(id)
);
create index if not exists idx_ms_recipe on mash_step(recipe_id);
