-- BJCP styles and link from beer

create table if not exists bjcp_style (
  id bigint generated by default as identity primary key,
  code varchar(16) not null,
  name varchar(255) not null,
  category varchar(255),
  subcategory varchar(32),
  guideline_year integer,
  og_min double precision,
  og_max double precision,
  fg_min double precision,
  fg_max double precision,
  ibu_min double precision,
  ibu_max double precision,
  abv_min double precision,
  abv_max double precision,
  srm_min double precision,
  srm_max double precision,
  notes varchar(2000),
  constraint uq_bjcp_code_year unique (code, guideline_year)
);

alter table beer add column if not exists style_ref_id bigint;
alter table beer add constraint fk_beer_style_ref foreign key (style_ref_id) references bjcp_style(id);
create index if not exists idx_beer_style_ref on beer(style_ref_id);
